apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-predictor-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: price-predictor
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: price-predictor
    spec:
      containers:
      - name: price-predictor-pod
        image: 195011/price-predictor:1.0
        ports:
        - containerPort: 80