apiVersion: v1
kind: Service
metadata:
  name: price-predictor-svc
  labels:
    app: price-predictor
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30002
    targetPort: 80
    protocol: TCP
  selector:
    app: price-predictor